// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mediator.proto

#include "mediator.pb.h"
#include "mediator.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace mediator {

static const char* AsrService_method_names[] = {
  "/mediator.AsrService/StreamingRecognize",
};

std::unique_ptr< AsrService::Stub> AsrService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AsrService::Stub> stub(new AsrService::Stub(channel));
  return stub;
}

AsrService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_StreamingRecognize_(AsrService_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>* AsrService::Stub::StreamingRecognizeRaw(::grpc::ClientContext* context) {
  return ::grpc_impl::internal::ClientReaderWriterFactory< ::mediator::AsrRequest, ::mediator::AsrResponse>::Create(channel_.get(), rpcmethod_StreamingRecognize_, context);
}

void AsrService::Stub::experimental_async::StreamingRecognize(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::mediator::AsrRequest,::mediator::AsrResponse>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderWriterFactory< ::mediator::AsrRequest,::mediator::AsrResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamingRecognize_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>* AsrService::Stub::AsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::mediator::AsrRequest, ::mediator::AsrResponse>::Create(channel_.get(), cq, rpcmethod_StreamingRecognize_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>* AsrService::Stub::PrepareAsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::mediator::AsrRequest, ::mediator::AsrResponse>::Create(channel_.get(), cq, rpcmethod_StreamingRecognize_, context, false, nullptr);
}

AsrService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AsrService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< AsrService::Service, ::mediator::AsrRequest, ::mediator::AsrResponse>(
          [](AsrService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             ::grpc_impl::ServerReaderWriter<::mediator::AsrResponse,
             ::mediator::AsrRequest>* stream) {
               return service->StreamingRecognize(ctx, stream);
             }, this)));
}

AsrService::Service::~Service() {
}

::grpc::Status AsrService::Service::StreamingRecognize(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::mediator::AsrResponse, ::mediator::AsrRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* LlmService_method_names[] = {
  "/mediator.LlmService/Generate",
};

std::unique_ptr< LlmService::Stub> LlmService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LlmService::Stub> stub(new LlmService::Stub(channel));
  return stub;
}

LlmService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Generate_(LlmService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LlmService::Stub::Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::mediator::LlmResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Generate_, context, request, response);
}

void LlmService::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, std::move(f));
}

void LlmService::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::LlmResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, std::move(f));
}

void LlmService::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, reactor);
}

void LlmService::Stub::experimental_async::Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::LlmResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Generate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mediator::LlmResponse>* LlmService::Stub::AsyncGenerateRaw(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mediator::LlmResponse>::Create(channel_.get(), cq, rpcmethod_Generate_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mediator::LlmResponse>* LlmService::Stub::PrepareAsyncGenerateRaw(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mediator::LlmResponse>::Create(channel_.get(), cq, rpcmethod_Generate_, context, request, false);
}

LlmService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LlmService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LlmService::Service, ::mediator::LlmRequest, ::mediator::LlmResponse>(
          [](LlmService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::mediator::LlmRequest* req,
             ::mediator::LlmResponse* resp) {
               return service->Generate(ctx, req, resp);
             }, this)));
}

LlmService::Service::~Service() {
}

::grpc::Status LlmService::Service::Generate(::grpc::ServerContext* context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* TtsService_method_names[] = {
  "/mediator.TtsService/Synth",
};

std::unique_ptr< TtsService::Stub> TtsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TtsService::Stub> stub(new TtsService::Stub(channel));
  return stub;
}

TtsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Synth_(TtsService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TtsService::Stub::Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::mediator::TtsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Synth_, context, request, response);
}

void TtsService::Stub::experimental_async::Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Synth_, context, request, response, std::move(f));
}

void TtsService::Stub::experimental_async::Synth(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::TtsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Synth_, context, request, response, std::move(f));
}

void TtsService::Stub::experimental_async::Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Synth_, context, request, response, reactor);
}

void TtsService::Stub::experimental_async::Synth(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::TtsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Synth_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mediator::TtsResponse>* TtsService::Stub::AsyncSynthRaw(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mediator::TtsResponse>::Create(channel_.get(), cq, rpcmethod_Synth_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mediator::TtsResponse>* TtsService::Stub::PrepareAsyncSynthRaw(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mediator::TtsResponse>::Create(channel_.get(), cq, rpcmethod_Synth_, context, request, false);
}

TtsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TtsService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TtsService::Service, ::mediator::TtsRequest, ::mediator::TtsResponse>(
          [](TtsService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::mediator::TtsRequest* req,
             ::mediator::TtsResponse* resp) {
               return service->Synth(ctx, req, resp);
             }, this)));
}

TtsService::Service::~Service() {
}

::grpc::Status TtsService::Service::Synth(::grpc::ServerContext* context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* BusinessService_method_names[] = {
  "/mediator.BusinessService/Control",
};

std::unique_ptr< BusinessService::Stub> BusinessService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BusinessService::Stub> stub(new BusinessService::Stub(channel));
  return stub;
}

BusinessService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Control_(BusinessService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BusinessService::Stub::Control(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::mediator::ControlResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Control_, context, request, response);
}

void BusinessService::Stub::experimental_async::Control(::grpc::ClientContext* context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Control_, context, request, response, std::move(f));
}

void BusinessService::Stub::experimental_async::Control(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::ControlResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Control_, context, request, response, std::move(f));
}

void BusinessService::Stub::experimental_async::Control(::grpc::ClientContext* context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Control_, context, request, response, reactor);
}

void BusinessService::Stub::experimental_async::Control(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::ControlResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Control_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mediator::ControlResponse>* BusinessService::Stub::AsyncControlRaw(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mediator::ControlResponse>::Create(channel_.get(), cq, rpcmethod_Control_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mediator::ControlResponse>* BusinessService::Stub::PrepareAsyncControlRaw(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mediator::ControlResponse>::Create(channel_.get(), cq, rpcmethod_Control_, context, request, false);
}

BusinessService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BusinessService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BusinessService::Service, ::mediator::ControlRequest, ::mediator::ControlResponse>(
          [](BusinessService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::mediator::ControlRequest* req,
             ::mediator::ControlResponse* resp) {
               return service->Control(ctx, req, resp);
             }, this)));
}

BusinessService::Service::~Service() {
}

::grpc::Status BusinessService::Service::Control(::grpc::ServerContext* context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* MemoryService_method_names[] = {
  "/mediator.MemoryService/FetchContext",
};

std::unique_ptr< MemoryService::Stub> MemoryService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MemoryService::Stub> stub(new MemoryService::Stub(channel));
  return stub;
}

MemoryService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_FetchContext_(MemoryService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MemoryService::Stub::FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::mediator::MemoryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_FetchContext_, context, request, response);
}

void MemoryService::Stub::experimental_async::FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_FetchContext_, context, request, response, std::move(f));
}

void MemoryService::Stub::experimental_async::FetchContext(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::MemoryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_FetchContext_, context, request, response, std::move(f));
}

void MemoryService::Stub::experimental_async::FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_FetchContext_, context, request, response, reactor);
}

void MemoryService::Stub::experimental_async::FetchContext(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::MemoryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_FetchContext_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mediator::MemoryResponse>* MemoryService::Stub::AsyncFetchContextRaw(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mediator::MemoryResponse>::Create(channel_.get(), cq, rpcmethod_FetchContext_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::mediator::MemoryResponse>* MemoryService::Stub::PrepareAsyncFetchContextRaw(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::mediator::MemoryResponse>::Create(channel_.get(), cq, rpcmethod_FetchContext_, context, request, false);
}

MemoryService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemoryService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemoryService::Service, ::mediator::MemoryRequest, ::mediator::MemoryResponse>(
          [](MemoryService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::mediator::MemoryRequest* req,
             ::mediator::MemoryResponse* resp) {
               return service->FetchContext(ctx, req, resp);
             }, this)));
}

MemoryService::Service::~Service() {
}

::grpc::Status MemoryService::Service::FetchContext(::grpc::ServerContext* context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mediator

