// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mediator.proto
// Original file comments:
// ============================================================================
// mediator.proto — 网关与后端微服务的 gRPC 接口契约
//
// 所有方法均通过 client context metadata "x-session-id" 携带会话 ID
// （16 字节 SessionId 的 hex 编码），供边车做一致性哈希粘性路由。
// ============================================================================
#ifndef GRPC_mediator_2eproto__INCLUDED
#define GRPC_mediator_2eproto__INCLUDED

#include "mediator.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace mediator {

// ---- ASR：双向流式语音识别 ----
class AsrService final {
 public:
  static constexpr char const* service_full_name() {
    return "mediator.AsrService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::mediator::AsrRequest, ::mediator::AsrResponse>> StreamingRecognize(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::mediator::AsrRequest, ::mediator::AsrResponse>>(StreamingRecognizeRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mediator::AsrRequest, ::mediator::AsrResponse>> AsyncStreamingRecognize(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mediator::AsrRequest, ::mediator::AsrResponse>>(AsyncStreamingRecognizeRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mediator::AsrRequest, ::mediator::AsrResponse>> PrepareAsyncStreamingRecognize(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::mediator::AsrRequest, ::mediator::AsrResponse>>(PrepareAsyncStreamingRecognizeRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StreamingRecognize(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mediator::AsrRequest,::mediator::AsrResponse>* reactor) = 0;
      #else
      virtual void StreamingRecognize(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::mediator::AsrRequest,::mediator::AsrResponse>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::mediator::AsrRequest, ::mediator::AsrResponse>* StreamingRecognizeRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::mediator::AsrRequest, ::mediator::AsrResponse>* AsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::mediator::AsrRequest, ::mediator::AsrResponse>* PrepareAsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>> StreamingRecognize(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>>(StreamingRecognizeRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>> AsyncStreamingRecognize(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>>(AsyncStreamingRecognizeRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>> PrepareAsyncStreamingRecognize(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>>(PrepareAsyncStreamingRecognizeRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StreamingRecognize(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::mediator::AsrRequest,::mediator::AsrResponse>* reactor) override;
      #else
      void StreamingRecognize(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::mediator::AsrRequest,::mediator::AsrResponse>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>* StreamingRecognizeRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>* AsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::mediator::AsrRequest, ::mediator::AsrResponse>* PrepareAsyncStreamingRecognizeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamingRecognize_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamingRecognize(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::mediator::AsrResponse, ::mediator::AsrRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamingRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamingRecognize() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamingRecognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingRecognize(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mediator::AsrResponse, ::mediator::AsrRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingRecognize(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::mediator::AsrResponse, ::mediator::AsrRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamingRecognize<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StreamingRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StreamingRecognize() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackBidiHandler< ::mediator::AsrRequest, ::mediator::AsrResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->StreamingRecognize(context); }));
    }
    ~ExperimentalWithCallbackMethod_StreamingRecognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingRecognize(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mediator::AsrResponse, ::mediator::AsrRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::mediator::AsrRequest, ::mediator::AsrResponse>* StreamingRecognize(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::mediator::AsrRequest, ::mediator::AsrResponse>* StreamingRecognize(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_StreamingRecognize<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_StreamingRecognize<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamingRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamingRecognize() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamingRecognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingRecognize(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mediator::AsrResponse, ::mediator::AsrRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamingRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamingRecognize() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamingRecognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingRecognize(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mediator::AsrResponse, ::mediator::AsrRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamingRecognize(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StreamingRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StreamingRecognize() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->StreamingRecognize(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_StreamingRecognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamingRecognize(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::mediator::AsrResponse, ::mediator::AsrRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamingRecognize(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamingRecognize(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

// ---- LLM：大模型文本生成（quick/restate/answer/quick_placeholder 共用） ----
class LlmService final {
 public:
  static constexpr char const* service_full_name() {
    return "mediator.LlmService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::mediator::LlmResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::LlmResponse>> AsyncGenerate(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::LlmResponse>>(AsyncGenerateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::LlmResponse>> PrepareAsyncGenerate(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::LlmResponse>>(PrepareAsyncGenerateRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::LlmResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::LlmResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::LlmResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mediator::LlmResponse>* AsyncGenerateRaw(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mediator::LlmResponse>* PrepareAsyncGenerateRaw(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::mediator::LlmResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::LlmResponse>> AsyncGenerate(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::LlmResponse>>(AsyncGenerateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::LlmResponse>> PrepareAsyncGenerate(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::LlmResponse>>(PrepareAsyncGenerateRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response, std::function<void(::grpc::Status)>) override;
      void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::LlmResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Generate(::grpc::ClientContext* context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::LlmResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Generate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::LlmResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mediator::LlmResponse>* AsyncGenerateRaw(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mediator::LlmResponse>* PrepareAsyncGenerateRaw(::grpc::ClientContext* context, const ::mediator::LlmRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Generate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Generate(::grpc::ServerContext* context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Generate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::mediator::LlmRequest* /*request*/, ::mediator::LlmResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerate(::grpc::ServerContext* context, ::mediator::LlmRequest* request, ::grpc::ServerAsyncResponseWriter< ::mediator::LlmResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Generate<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Generate() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::mediator::LlmRequest, ::mediator::LlmResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::mediator::LlmRequest* request, ::mediator::LlmResponse* response) { return this->Generate(context, request, response); }));}
    void SetMessageAllocatorFor_Generate(
        ::grpc::experimental::MessageAllocator< ::mediator::LlmRequest, ::mediator::LlmResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::mediator::LlmRequest, ::mediator::LlmResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::mediator::LlmRequest* /*request*/, ::mediator::LlmResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Generate(
      ::grpc::CallbackServerContext* /*context*/, const ::mediator::LlmRequest* /*request*/, ::mediator::LlmResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Generate(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::mediator::LlmRequest* /*request*/, ::mediator::LlmResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Generate<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Generate<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Generate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::mediator::LlmRequest* /*request*/, ::mediator::LlmResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Generate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::mediator::LlmRequest* /*request*/, ::mediator::LlmResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Generate() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Generate(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::mediator::LlmRequest* /*request*/, ::mediator::LlmResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Generate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Generate(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Generate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mediator::LlmRequest, ::mediator::LlmResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::mediator::LlmRequest, ::mediator::LlmResponse>* streamer) {
                       return this->StreamedGenerate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Generate(::grpc::ServerContext* /*context*/, const ::mediator::LlmRequest* /*request*/, ::mediator::LlmResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGenerate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mediator::LlmRequest,::mediator::LlmResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Generate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Generate<Service > StreamedService;
};

// ---- TTS：文本转语音 ----
class TtsService final {
 public:
  static constexpr char const* service_full_name() {
    return "mediator.TtsService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::mediator::TtsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::TtsResponse>> AsyncSynth(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::TtsResponse>>(AsyncSynthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::TtsResponse>> PrepareAsyncSynth(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::TtsResponse>>(PrepareAsyncSynthRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Synth(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::TtsResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Synth(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::TtsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Synth(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::TtsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mediator::TtsResponse>* AsyncSynthRaw(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mediator::TtsResponse>* PrepareAsyncSynthRaw(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::mediator::TtsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::TtsResponse>> AsyncSynth(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::TtsResponse>>(AsyncSynthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::TtsResponse>> PrepareAsyncSynth(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::TtsResponse>>(PrepareAsyncSynthRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response, std::function<void(::grpc::Status)>) override;
      void Synth(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::TtsResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Synth(::grpc::ClientContext* context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Synth(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::TtsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Synth(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::TtsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mediator::TtsResponse>* AsyncSynthRaw(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mediator::TtsResponse>* PrepareAsyncSynthRaw(::grpc::ClientContext* context, const ::mediator::TtsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Synth_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Synth(::grpc::ServerContext* context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Synth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Synth() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Synth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Synth(::grpc::ServerContext* /*context*/, const ::mediator::TtsRequest* /*request*/, ::mediator::TtsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSynth(::grpc::ServerContext* context, ::mediator::TtsRequest* request, ::grpc::ServerAsyncResponseWriter< ::mediator::TtsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Synth<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Synth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Synth() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::mediator::TtsRequest, ::mediator::TtsResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::mediator::TtsRequest* request, ::mediator::TtsResponse* response) { return this->Synth(context, request, response); }));}
    void SetMessageAllocatorFor_Synth(
        ::grpc::experimental::MessageAllocator< ::mediator::TtsRequest, ::mediator::TtsResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::mediator::TtsRequest, ::mediator::TtsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Synth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Synth(::grpc::ServerContext* /*context*/, const ::mediator::TtsRequest* /*request*/, ::mediator::TtsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Synth(
      ::grpc::CallbackServerContext* /*context*/, const ::mediator::TtsRequest* /*request*/, ::mediator::TtsResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Synth(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::mediator::TtsRequest* /*request*/, ::mediator::TtsResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Synth<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Synth<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Synth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Synth() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Synth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Synth(::grpc::ServerContext* /*context*/, const ::mediator::TtsRequest* /*request*/, ::mediator::TtsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Synth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Synth() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Synth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Synth(::grpc::ServerContext* /*context*/, const ::mediator::TtsRequest* /*request*/, ::mediator::TtsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSynth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Synth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Synth() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Synth(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Synth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Synth(::grpc::ServerContext* /*context*/, const ::mediator::TtsRequest* /*request*/, ::mediator::TtsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Synth(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Synth(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Synth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Synth() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mediator::TtsRequest, ::mediator::TtsResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::mediator::TtsRequest, ::mediator::TtsResponse>* streamer) {
                       return this->StreamedSynth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Synth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Synth(::grpc::ServerContext* /*context*/, const ::mediator::TtsRequest* /*request*/, ::mediator::TtsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSynth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mediator::TtsRequest,::mediator::TtsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Synth<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Synth<Service > StreamedService;
};

// ---- 业务控制指令 ----
class BusinessService final {
 public:
  static constexpr char const* service_full_name() {
    return "mediator.BusinessService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Control(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::mediator::ControlResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::ControlResponse>> AsyncControl(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::ControlResponse>>(AsyncControlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::ControlResponse>> PrepareAsyncControl(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::ControlResponse>>(PrepareAsyncControlRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Control(::grpc::ClientContext* context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Control(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::ControlResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Control(::grpc::ClientContext* context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Control(::grpc::ClientContext* context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Control(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::ControlResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Control(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::ControlResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mediator::ControlResponse>* AsyncControlRaw(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mediator::ControlResponse>* PrepareAsyncControlRaw(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Control(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::mediator::ControlResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::ControlResponse>> AsyncControl(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::ControlResponse>>(AsyncControlRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::ControlResponse>> PrepareAsyncControl(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::ControlResponse>>(PrepareAsyncControlRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Control(::grpc::ClientContext* context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response, std::function<void(::grpc::Status)>) override;
      void Control(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::ControlResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Control(::grpc::ClientContext* context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Control(::grpc::ClientContext* context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Control(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::ControlResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Control(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::ControlResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mediator::ControlResponse>* AsyncControlRaw(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mediator::ControlResponse>* PrepareAsyncControlRaw(::grpc::ClientContext* context, const ::mediator::ControlRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Control_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Control(::grpc::ServerContext* context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Control() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, const ::mediator::ControlRequest* /*request*/, ::mediator::ControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestControl(::grpc::ServerContext* context, ::mediator::ControlRequest* request, ::grpc::ServerAsyncResponseWriter< ::mediator::ControlResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Control<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Control() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::mediator::ControlRequest, ::mediator::ControlResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::mediator::ControlRequest* request, ::mediator::ControlResponse* response) { return this->Control(context, request, response); }));}
    void SetMessageAllocatorFor_Control(
        ::grpc::experimental::MessageAllocator< ::mediator::ControlRequest, ::mediator::ControlResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::mediator::ControlRequest, ::mediator::ControlResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, const ::mediator::ControlRequest* /*request*/, ::mediator::ControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Control(
      ::grpc::CallbackServerContext* /*context*/, const ::mediator::ControlRequest* /*request*/, ::mediator::ControlResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Control(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::mediator::ControlRequest* /*request*/, ::mediator::ControlResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Control<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Control<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Control() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, const ::mediator::ControlRequest* /*request*/, ::mediator::ControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Control() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, const ::mediator::ControlRequest* /*request*/, ::mediator::ControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestControl(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Control() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Control(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, const ::mediator::ControlRequest* /*request*/, ::mediator::ControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Control(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Control(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Control : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Control() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mediator::ControlRequest, ::mediator::ControlResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::mediator::ControlRequest, ::mediator::ControlResponse>* streamer) {
                       return this->StreamedControl(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Control() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Control(::grpc::ServerContext* /*context*/, const ::mediator::ControlRequest* /*request*/, ::mediator::ControlResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedControl(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mediator::ControlRequest,::mediator::ControlResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Control<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Control<Service > StreamedService;
};

// ---- 记忆服务：长期离线会话的上下文收割 ----
class MemoryService final {
 public:
  static constexpr char const* service_full_name() {
    return "mediator.MemoryService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::mediator::MemoryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::MemoryResponse>> AsyncFetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::MemoryResponse>>(AsyncFetchContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::MemoryResponse>> PrepareAsyncFetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediator::MemoryResponse>>(PrepareAsyncFetchContextRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FetchContext(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::MemoryResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void FetchContext(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::MemoryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void FetchContext(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::MemoryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mediator::MemoryResponse>* AsyncFetchContextRaw(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mediator::MemoryResponse>* PrepareAsyncFetchContextRaw(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::mediator::MemoryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::MemoryResponse>> AsyncFetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::MemoryResponse>>(AsyncFetchContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::MemoryResponse>> PrepareAsyncFetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediator::MemoryResponse>>(PrepareAsyncFetchContextRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response, std::function<void(::grpc::Status)>) override;
      void FetchContext(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::MemoryResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void FetchContext(::grpc::ClientContext* context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void FetchContext(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::MemoryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void FetchContext(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::mediator::MemoryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mediator::MemoryResponse>* AsyncFetchContextRaw(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mediator::MemoryResponse>* PrepareAsyncFetchContextRaw(::grpc::ClientContext* context, const ::mediator::MemoryRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FetchContext_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FetchContext(::grpc::ServerContext* context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FetchContext() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FetchContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchContext(::grpc::ServerContext* /*context*/, const ::mediator::MemoryRequest* /*request*/, ::mediator::MemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchContext(::grpc::ServerContext* context, ::mediator::MemoryRequest* request, ::grpc::ServerAsyncResponseWriter< ::mediator::MemoryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FetchContext<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_FetchContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_FetchContext() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::mediator::MemoryRequest, ::mediator::MemoryResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::mediator::MemoryRequest* request, ::mediator::MemoryResponse* response) { return this->FetchContext(context, request, response); }));}
    void SetMessageAllocatorFor_FetchContext(
        ::grpc::experimental::MessageAllocator< ::mediator::MemoryRequest, ::mediator::MemoryResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::mediator::MemoryRequest, ::mediator::MemoryResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_FetchContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchContext(::grpc::ServerContext* /*context*/, const ::mediator::MemoryRequest* /*request*/, ::mediator::MemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FetchContext(
      ::grpc::CallbackServerContext* /*context*/, const ::mediator::MemoryRequest* /*request*/, ::mediator::MemoryResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FetchContext(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::mediator::MemoryRequest* /*request*/, ::mediator::MemoryResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_FetchContext<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_FetchContext<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FetchContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FetchContext() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FetchContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchContext(::grpc::ServerContext* /*context*/, const ::mediator::MemoryRequest* /*request*/, ::mediator::MemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FetchContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FetchContext() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FetchContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchContext(::grpc::ServerContext* /*context*/, const ::mediator::MemoryRequest* /*request*/, ::mediator::MemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchContext(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_FetchContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_FetchContext() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FetchContext(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_FetchContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchContext(::grpc::ServerContext* /*context*/, const ::mediator::MemoryRequest* /*request*/, ::mediator::MemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* FetchContext(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* FetchContext(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FetchContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FetchContext() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mediator::MemoryRequest, ::mediator::MemoryResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::mediator::MemoryRequest, ::mediator::MemoryResponse>* streamer) {
                       return this->StreamedFetchContext(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FetchContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FetchContext(::grpc::ServerContext* /*context*/, const ::mediator::MemoryRequest* /*request*/, ::mediator::MemoryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFetchContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mediator::MemoryRequest,::mediator::MemoryResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FetchContext<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_FetchContext<Service > StreamedService;
};

}  // namespace mediator


#endif  // GRPC_mediator_2eproto__INCLUDED
