add_test( CopyChannel.DeepCopyOnSend /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=CopyChannel.DeepCopyOnSend]==] --gtest_also_run_disabled_tests)
set_tests_properties( CopyChannel.DeepCopyOnSend PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CopyChannel.SwapOutAllDrainsQueue /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=CopyChannel.SwapOutAllDrainsQueue]==] --gtest_also_run_disabled_tests)
set_tests_properties( CopyChannel.SwapOutAllDrainsQueue PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CopyChannel.BlockingRecvUnblocksOnClose /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=CopyChannel.BlockingRecvUnblocksOnClose]==] --gtest_also_run_disabled_tests)
set_tests_properties( CopyChannel.BlockingRecvUnblocksOnClose PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( PriorityTimer.ExecutesInDueOrder /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=PriorityTimer.ExecutesInDueOrder]==] --gtest_also_run_disabled_tests)
set_tests_properties( PriorityTimer.ExecutesInDueOrder PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( PriorityTimer.SkippableTaskDroppedWhenLateOver1s /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=PriorityTimer.SkippableTaskDroppedWhenLateOver1s]==] --gtest_also_run_disabled_tests)
set_tests_properties( PriorityTimer.SkippableTaskDroppedWhenLateOver1s PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( PriorityTimer.MessageTaskNeverSkipped /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=PriorityTimer.MessageTaskNeverSkipped]==] --gtest_also_run_disabled_tests)
set_tests_properties( PriorityTimer.MessageTaskNeverSkipped PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( PriorityTimer.SkippableRunsWhenWithinThreshold /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=PriorityTimer.SkippableRunsWhenWithinThreshold]==] --gtest_also_run_disabled_tests)
set_tests_properties( PriorityTimer.SkippableRunsWhenWithinThreshold PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Reactor.TaskIdsIncreaseAndStatsRecorded /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Reactor.TaskIdsIncreaseAndStatsRecorded]==] --gtest_also_run_disabled_tests)
set_tests_properties( Reactor.TaskIdsIncreaseAndStatsRecorded PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Reactor.SlowCpuTaskTriggersWarn /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Reactor.SlowCpuTaskTriggersWarn]==] --gtest_also_run_disabled_tests)
set_tests_properties( Reactor.SlowCpuTaskTriggersWarn PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Reactor.IoTaskThresholdIs1s /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Reactor.IoTaskThresholdIs1s]==] --gtest_also_run_disabled_tests)
set_tests_properties( Reactor.IoTaskThresholdIs1s PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( G711.RoundTripSmallError /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=G711.RoundTripSmallError]==] --gtest_also_run_disabled_tests)
set_tests_properties( G711.RoundTripSmallError PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( G711.ZeroRoundTrip /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=G711.ZeroRoundTrip]==] --gtest_also_run_disabled_tests)
set_tests_properties( G711.ZeroRoundTrip PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( G711.VectorCodecLength /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=G711.VectorCodecLength]==] --gtest_also_run_disabled_tests)
set_tests_properties( G711.VectorCodecLength PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Watermark.DetectsDelayAndSkewWithinTolerance /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Watermark.DetectsDelayAndSkewWithinTolerance]==] --gtest_also_run_disabled_tests)
set_tests_properties( Watermark.DetectsDelayAndSkewWithinTolerance PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Watermark.NegativeSkewDetected /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Watermark.NegativeSkewDetected]==] --gtest_also_run_disabled_tests)
set_tests_properties( Watermark.NegativeSkewDetected PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Watermark.NoFalsePositiveOnSilence /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Watermark.NoFalsePositiveOnSilence]==] --gtest_also_run_disabled_tests)
set_tests_properties( Watermark.NoFalsePositiveOnSilence PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Watermark.NoFalsePositiveOnPureNoise /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Watermark.NoFalsePositiveOnPureNoise]==] --gtest_also_run_disabled_tests)
set_tests_properties( Watermark.NoFalsePositiveOnPureNoise PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Watermark.SingleChirpRejected /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Watermark.SingleChirpRejected]==] --gtest_also_run_disabled_tests)
set_tests_properties( Watermark.SingleChirpRejected PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Watermark.DetectsAtBufferStart /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Watermark.DetectsAtBufferStart]==] --gtest_also_run_disabled_tests)
set_tests_properties( Watermark.DetectsAtBufferStart PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Watermark.SurvivesG711Distortion /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Watermark.SurvivesG711Distortion]==] --gtest_also_run_disabled_tests)
set_tests_properties( Watermark.SurvivesG711Distortion PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Align.ResampleLengthFollowsSkew /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Align.ResampleLengthFollowsSkew]==] --gtest_also_run_disabled_tests)
set_tests_properties( Align.ResampleLengthFollowsSkew PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Align.ResamplePreservesSine /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Align.ResamplePreservesSine]==] --gtest_also_run_disabled_tests)
set_tests_properties( Align.ResamplePreservesSine PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Align.DelayLineShiftsExactly /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Align.DelayLineShiftsExactly]==] --gtest_also_run_disabled_tests)
set_tests_properties( Align.DelayLineShiftsExactly PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CtxEvict.UnderLimitUnchanged /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=CtxEvict.UnderLimitUnchanged]==] --gtest_also_run_disabled_tests)
set_tests_properties( CtxEvict.UnderLimitUnchanged PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CtxEvict.OverLimitDropsOldestToHalf /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=CtxEvict.OverLimitDropsOldestToHalf]==] --gtest_also_run_disabled_tests)
set_tests_properties( CtxEvict.OverLimitDropsOldestToHalf PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CtxEvict.AlignsToLineBoundary /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=CtxEvict.AlignsToLineBoundary]==] --gtest_also_run_disabled_tests)
set_tests_properties( CtxEvict.AlignsToLineBoundary PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CtxEvict.NoNewlineKeepsTail /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=CtxEvict.NoNewlineKeepsTail]==] --gtest_also_run_disabled_tests)
set_tests_properties( CtxEvict.NoNewlineKeepsTail PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Auth.BuiltinExtractsUid /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Auth.BuiltinExtractsUid]==] --gtest_also_run_disabled_tests)
set_tests_properties( Auth.BuiltinExtractsUid PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Auth.BuiltinRejectsBadFormat /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Auth.BuiltinRejectsBadFormat]==] --gtest_also_run_disabled_tests)
set_tests_properties( Auth.BuiltinRejectsBadFormat PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Auth.FailClosedOnWasmTrap /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Auth.FailClosedOnWasmTrap]==] --gtest_also_run_disabled_tests)
set_tests_properties( Auth.FailClosedOnWasmTrap PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Auth.UidDerivesDeterministicSessionId /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Auth.UidDerivesDeterministicSessionId]==] --gtest_also_run_disabled_tests)
set_tests_properties( Auth.UidDerivesDeterministicSessionId PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.ConnectSendsWatermarkAndDropsFrames /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.ConnectSendsWatermarkAndDropsFrames]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.ConnectSendsWatermarkAndDropsFrames PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.WmDetectedCompletesCalib /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.WmDetectedCompletesCalib]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.WmDetectedCompletesCalib PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.QuickRespTriggersAfter5s /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.QuickRespTriggersAfter5s]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.QuickRespTriggersAfter5s PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.QuickRespTriggersOnVadEnd /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.QuickRespTriggersOnVadEnd]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.QuickRespTriggersOnVadEnd PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.QuickRespTriggersOnAsrEndpoint /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.QuickRespTriggersOnAsrEndpoint]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.QuickRespTriggersOnAsrEndpoint PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.QuickRespSubmittedOnlyOnce /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.QuickRespSubmittedOnlyOnce]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.QuickRespSubmittedOnlyOnce PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.AsrFinalSubmitsRestateAndAnswer /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.AsrFinalSubmitsRestateAndAnswer]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.AsrFinalSubmitsRestateAndAnswer PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.LlmTextTriggersTtsPerClip /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.LlmTextTriggersTtsPerClip]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.LlmTextTriggersTtsPerClip PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.PlaybackOrderSootheRestateAnswer /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.PlaybackOrderSootheRestateAnswer]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.PlaybackOrderSootheRestateAnswer PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.RestateTimeoutGeneratesPlaceholder /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.RestateTimeoutGeneratesPlaceholder]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.RestateTimeoutGeneratesPlaceholder PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.PlaceholderReusedWhenSootheNotReady /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.PlaceholderReusedWhenSootheNotReady]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.PlaceholderReusedWhenSootheNotReady PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.StallsAfterMaxPlaceholderRounds /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.StallsAfterMaxPlaceholderRounds]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.StallsAfterMaxPlaceholderRounds PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.GcAfter3MinOfflineCallsMemoryAndCleans /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.GcAfter3MinOfflineCallsMemoryAndCleans]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.GcAfter3MinOfflineCallsMemoryAndCleans PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.ReconnectWithin3MinKeepsContextAndCalib /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.ReconnectWithin3MinKeepsContextAndCalib]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.ReconnectWithin3MinKeepsContextAndCalib PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.OldGenerationMessageDiscarded /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.OldGenerationMessageDiscarded]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.OldGenerationMessageDiscarded PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.CtxEvictedOver1MbAndSyncedToRedis /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.CtxEvictedOver1MbAndSyncedToRedis]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.CtxEvictedOver1MbAndSyncedToRedis PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Fixture.DeterministicReplay /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Fixture.DeterministicReplay]==] --gtest_also_run_disabled_tests)
set_tests_properties( Fixture.DeterministicReplay PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Wasm3Auth.AllowModuleAcceptsMagicToken /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Wasm3Auth.AllowModuleAcceptsMagicToken]==] --gtest_also_run_disabled_tests)
set_tests_properties( Wasm3Auth.AllowModuleAcceptsMagicToken PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Wasm3Auth.AllowModuleRejectsWrongToken /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Wasm3Auth.AllowModuleRejectsWrongToken]==] --gtest_also_run_disabled_tests)
set_tests_properties( Wasm3Auth.AllowModuleRejectsWrongToken PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Wasm3Auth.TrapModuleFailsClosed /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Wasm3Auth.TrapModuleFailsClosed]==] --gtest_also_run_disabled_tests)
set_tests_properties( Wasm3Auth.TrapModuleFailsClosed PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Wasm3Auth.NullModuleFailsClosed /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Wasm3Auth.NullModuleFailsClosed]==] --gtest_also_run_disabled_tests)
set_tests_properties( Wasm3Auth.NullModuleFailsClosed PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( Wasm3Manager.LoadReplaceAndMissingKeepsOld /mnt/d/vit/mediator/build-wsl/tests/mediator_tests [==[--gtest_filter=Wasm3Manager.LoadReplaceAndMissingKeepsOld]==] --gtest_also_run_disabled_tests)
set_tests_properties( Wasm3Manager.LoadReplaceAndMissingKeepsOld PROPERTIES WORKING_DIRECTORY /mnt/d/vit/mediator/build-wsl/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( mediator_tests_TESTS CopyChannel.DeepCopyOnSend CopyChannel.SwapOutAllDrainsQueue CopyChannel.BlockingRecvUnblocksOnClose PriorityTimer.ExecutesInDueOrder PriorityTimer.SkippableTaskDroppedWhenLateOver1s PriorityTimer.MessageTaskNeverSkipped PriorityTimer.SkippableRunsWhenWithinThreshold Reactor.TaskIdsIncreaseAndStatsRecorded Reactor.SlowCpuTaskTriggersWarn Reactor.IoTaskThresholdIs1s G711.RoundTripSmallError G711.ZeroRoundTrip G711.VectorCodecLength Watermark.DetectsDelayAndSkewWithinTolerance Watermark.NegativeSkewDetected Watermark.NoFalsePositiveOnSilence Watermark.NoFalsePositiveOnPureNoise Watermark.SingleChirpRejected Watermark.DetectsAtBufferStart Watermark.SurvivesG711Distortion Align.ResampleLengthFollowsSkew Align.ResamplePreservesSine Align.DelayLineShiftsExactly CtxEvict.UnderLimitUnchanged CtxEvict.OverLimitDropsOldestToHalf CtxEvict.AlignsToLineBoundary CtxEvict.NoNewlineKeepsTail Auth.BuiltinExtractsUid Auth.BuiltinRejectsBadFormat Auth.FailClosedOnWasmTrap Auth.UidDerivesDeterministicSessionId Fixture.ConnectSendsWatermarkAndDropsFrames Fixture.WmDetectedCompletesCalib Fixture.QuickRespTriggersAfter5s Fixture.QuickRespTriggersOnVadEnd Fixture.QuickRespTriggersOnAsrEndpoint Fixture.QuickRespSubmittedOnlyOnce Fixture.AsrFinalSubmitsRestateAndAnswer Fixture.LlmTextTriggersTtsPerClip Fixture.PlaybackOrderSootheRestateAnswer Fixture.RestateTimeoutGeneratesPlaceholder Fixture.PlaceholderReusedWhenSootheNotReady Fixture.StallsAfterMaxPlaceholderRounds Fixture.GcAfter3MinOfflineCallsMemoryAndCleans Fixture.ReconnectWithin3MinKeepsContextAndCalib Fixture.OldGenerationMessageDiscarded Fixture.CtxEvictedOver1MbAndSyncedToRedis Fixture.DeterministicReplay Wasm3Auth.AllowModuleAcceptsMagicToken Wasm3Auth.AllowModuleRejectsWrongToken Wasm3Auth.TrapModuleFailsClosed Wasm3Auth.NullModuleFailsClosed Wasm3Manager.LoadReplaceAndMissingKeepsOld)
